from sqlalchemy import Column, Integer, String, Text, Float, ForeignKey, Boolean
from sqlalchemy.orm import relationship

from database import Base


class Project(Base):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    budget = Column(Integer, nullable=False)

    milestones = relationship("Milestone", back_populates="project", cascade="all, delete-orphan")
    submissions = relationship("Submission", back_populates="project", cascade="all, delete-orphan")


class Milestone(Base):
    __tablename__ = "milestones"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False, index=True)

    milestone_id = Column(Integer, nullable=False)  # 1, 2, 3... as generated by AI
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    completion_criteria = Column(Text, nullable=False)
    payment_percentage = Column(Float, nullable=False)
    deadline_days = Column(Integer, nullable=False)

    project = relationship("Project", back_populates="milestones")


class Submission(Base):
    __tablename__ = "submissions"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False, index=True)
    milestone_id = Column(Integer, nullable=False, index=True)
    work_link = Column(Text, nullable=False)

    # Evaluation fields populated when /verify/work is called
    verdict = Column(String(50), nullable=True)  # completed / partial / failed
    score = Column(Integer, nullable=True)  # 0–100
    feedback = Column(Text, nullable=True)
    release_payment = Column(Boolean, nullable=True)
    partial_payment_percentage = Column(Integer, nullable=True)

    project = relationship("Project", back_populates="submissions")

